# 1. Creating Pandas Series and Data Frames

Let's practice everything that we have learnt together so far by creating some pandas series and dataframes! This information that you have in here corresponds to the number of locations (i.e. physical places, like London or Paris, also called GPE (Geo-Political Entities) in NER (Name Entity Recognition) found in a selection of novels written by Charles Dickens. 

   * A Christmas Carol, 7.
   * A Tale of Two Cities, 59.
   * Barnaby Rudge, 72.
   * Bleack House, 122.
   * David Copperfield, 113.
   * Dombey and Son, 98.
   * Great Expectations, 75.
   * Hard Times, 34.

### 1.1. Creating Pandas Series

Now please:
  * 1) Import the pandas library.
  * 2) Create two pandas series and store them in two different variables: one for novel titles, and another one containing the total number of GPE (Geo Political Entities) found at those novels.
  * 3) Check the data type of both variables and its length.
  * 4) Check the index of one of the variables using the .index method

In [10]:
# Your code in here

### 1.2. Creating Pands Dataframes

Let's use those two pandas Series that you have just created and let's put together a Dataframe. Please:

   * 1) Create a pandas dataframe firs only using the columns title. Use this code template: variable_name = pd.DataFrame(pandas_series, columns = ["Name of Column"]).
   * 2) Now add the locations column. 
   * 3) Let's try now creating a Data Frame using a dictionary where the name of the columns are the keys and the content of the columns are the variables that you have created (titles, locations) with the locations.

In [1]:
#Your code in here

# 2. Slicing Pandas Series and Pandas Dataframes

A new dataset that contains all the cities mentioned in all the novels written by Charles Dickens, and also the Latitude and Longitude has been created for you. Just run the following line of code:

In [24]:
data = pd.read_csv("dickens_coordinates.csv", index_col = 0)
data

         Location   Latitude   Longitude               Titles
0          Bedlam  54.048993   -1.592586    A Christmas Carol
1     Camden Town  51.539253   -0.142757    A Christmas Carol
2          London  51.507446   -0.127765    A Christmas Carol
3           Sheba  31.245744   34.792518    A Christmas Carol
4        Damascus  39.288438  -77.203872    A Christmas Carol
...           ...        ...         ...                  ...
1222      America  39.783730 -100.445882  The Pickwick Papers
1223       Wulter        NaN         NaN  The Pickwick Papers
1224      Dulwich  51.441879   -0.084324  The Pickwick Papers
1225     Richmond  37.538509  -77.434280  The Pickwick Papers
1226       Bengal  39.473504  -85.922900  The Pickwick Papers

[1227 rows x 4 columns]

### 2.1. Slicing Pandas Series

Now: 
   * 1. Please select the "Location" column using the name of the column. Store that into a new variable.
   * 2. Print the type of data and its length
   * 3. Select the first element in the variable
   * 4. Select elements 35-50 in the variable and store them in a different variable (so, new_variable = variable[34:87]
   * Multiple choice question for you:
       * a) Do you think that you have selected values 35-50?
       * b) Do you think that you have selected the real values 35-50? (taking into account the python 0 notation) or 34-49?(taking into account the python 0 notation and the weird end-of-list-minus-one thingy).
       * c) If your goal is to select real values 35-50: what do you have to write down? 
   * 5. Use the index method to check the index of your new variable (the one you created in point 4). Does it have a new index or it keeps the one that the first variable was created?
   * 6. Write a for loop where you add the text "Dickens" to all elements in the new variable (remember to have a blank space before you write Dickens!). Is this list or dictionary behaviour?
   * 7. Use the dictionary .keys method on your new variable. Is this list or dictionary behaviour?
   * 8. Try using the [-1] notation to select the last element in the pandas series. What happens?
   * 9. Convert your new variable into a list and now select the last element in that list.

In [25]:
# Your code in here

### 2. Slicing Pandas Dataframes.

Let's print again our dataframe (for visualization purposes)

In [44]:
data

         Location   Latitude   Longitude               Titles
0          Bedlam  54.048993   -1.592586    A Christmas Carol
1     Camden Town  51.539253   -0.142757    A Christmas Carol
2          London  51.507446   -0.127765    A Christmas Carol
3           Sheba  31.245744   34.792518    A Christmas Carol
4        Damascus  39.288438  -77.203872    A Christmas Carol
...           ...        ...         ...                  ...
1222      America  39.783730 -100.445882  The Pickwick Papers
1223       Wulter        NaN         NaN  The Pickwick Papers
1224      Dulwich  51.441879   -0.084324  The Pickwick Papers
1225     Richmond  37.538509  -77.434280  The Pickwick Papers
1226       Bengal  39.473504  -85.922900  The Pickwick Papers

[1227 rows x 4 columns]

And now let's do some Loc-Iloc and column slicing/selection stretching:
   * 1. Select the "Location" column just using the title of that column. Save it into a new variable. Check the data type.
   * 2. Using iloc (remember, "integer location"), create 4 new variables where you select:
       * The first column.
       * The first row
       * Rows 35-50 in the first two columns (Location and Latitude). (CAREFUL with the python 0 notation and the weird last element in the list thingy)
   * 3. Let's change the game and let's use Loc. Select rows 0-10 in column "Latitude". Save that into a variable.
   * 4. And now using loc select rows 0:20 in columns "Latitude" and "Longitude". Save that into a variable.
   * 5. Select the whole "Titles Column" (in any way you want). Check its data type. Use the pandas method .to_list() and transform it into a list.

In [45]:
# Your code in here